!###############################################################################
! MODULE THAT DEFINES GLOBAL CONSTANTS
!###############################################################################

      MODULE COMMON_VAR
      IMPLICIT NONE
      INTEGER :: I,J,K,Q
      SAVE
      CHARACTER(2),ALLOCATABLE,DIMENSION(:) :: ATOM
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: Z
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: AMU
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: C
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: X
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: Y,YY,YYY,W,WW
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: FVEC,DIFFC
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: DFVEC      
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: GAMAINIT
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: CBS
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:,:) :: XBS
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: YBS,YYBS,WBS,WWBS
      INTEGER,ALLOCATABLE,DIMENSION(:) :: MBS,NPBS,NCBS
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:) :: CPOL
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: GAMAFINAL,RREFFINAL,ZETAFINAL
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: GAMAINITPOL,RREFINITPOL,ZETAINITPOL
      DOUBLE PRECISION,ALLOCATABLE,DIMENSION(:,:) :: CBSINITPOL
      INTEGER :: NPMAX=100000
      INTEGER :: NCMAX=5000
      DOUBLE PRECISION :: EH2CM=219474.6313702D+00
      DOUBLE PRECISION :: ANGS2AU=0.5291772D+00
      DOUBLE PRECISION :: PI=3.14159265358979D+00
      DOUBLE PRECISION :: DEGS=180.00D+00
      INTEGER :: ERR,CONT,CONTDEG
      INTEGER :: NATOM,NX,NC,NP,NCPOL
      INTEGER :: NXRED
      INTEGER :: M,L,IOS
      DOUBLE PRECISION :: M1,M2
      CHARACTER(2) :: ATOMA, ATOMB
      DOUBLE PRECISION :: MA,MB,ZA,ZB
      DOUBLE PRECISION :: RREF0INIT,ZETAINIT
      DOUBLE PRECISION :: EZERO
      INTEGER :: INFO,DEG,EVALID
      CHARACTER(LEN=14) :: OPTTYP
      CHARACTER(LEN=14) :: JOBTYP
      CHARACTER(LEN=4) :: MOLTYP
      CHARACTER(LEN=10) :: MOL
      REAL :: START,FINAL
      INTEGER, PARAMETER :: NATOMMAX=100
      DOUBLE PRECISION, DIMENSION(3*NATOMMAX) :: CARTX
      DOUBLE PRECISION :: REEXP,DEEXP,WEEXP
      INTEGER :: NABINITIO,NROVIB
      DOUBLE PRECISION :: EXPFD,EXPSD
      INTEGER,ALLOCATABLE,DIMENSION(:) :: IVEXP,IJEXP
      DOUBLE PRECISION :: VLIM
      INTEGER, PARAMETER :: IVIBMX=400
      INTEGER, PARAMETER :: ITVIB=10000
      INTEGER :: ICHARGE,IOMEGA
      END MODULE COMMON_VAR
